module.exports = {
  EXTENSTIONS_DIR: 'extensions',
  BORON_DLC_DIR: 'ego_dlc_boron',
  PIRATE_DLC_DIR: 'ego_dlc_pirate',
  SPLIT_DLC_DIR: 'ego_dlc_split',
  TERRAN_DLC_DIR: 'ego_dlc_terran',
  REG_CAT: /^([\d_a-zA-Z]+)\.cat$/,
  REG_DAT: /^([\d_a-zA-Z]+)\.dat$/,
  REG_CAT_ROW: /^([a-zA-Z\d\s\-_()+',/\[\]\.]+\.[a-zA-Z\d]+) (\d+) (\d+) ([a-z\d]+)$/,
  REG_STRUCT_HABITAT: /^assets\/structures\/habitat\/macros/,
  STRUCT_HABITAT_SAVE: './assets_structures_habitat_macros',
  REG_STRUCT_PRODUCTION: /^assets\/structures\/production\/macros/,
  STRUCT_PRODUCTION_SAVE: './assets_structures_production_macros',
  REG_STRUCT_STORAGE: /^assets\/structures\/storage\/macros/,
  STRUCT_STORAGE_SAVE: './assets_structures_storage_macros',
  REG_WARES: /^libraries\/wares.xml$/,
  WARES_SAVE: './wares',
  REG_T: /^t\/\d{4}-l\d{3}.xml/,
  T_SAVE: './t',
  REG_MAP: /^maps\/xu_ep2_universe/,
  MAP_SAVE: './xu_ep2_universe',
  REG_MAP_DEFAULTS: /^libraries\/mapdefaults.xml$/,
  MAP_DEFAULTS_SAVE: './mapdefaults',
}
